"""Application-wide constants and configuration."""

APP_NAME = "Adzanid"
APP_TITLE = "Jadwal Sholat Indonesia"
APP_VERSION = "1.0.0"
SETTINGS_ORG = "Adzanid"
SETTINGS_APP = "Adzanid"

GITHUB_URL = "https://github.com/fikrisyahid/"
AUTHOR = "Fikri Syahid"
COPYRIGHT_YEAR = 2026

# Default adhan audio file path
DEFAULT_ADHAN_PATH = "assets/adzan.mp3"

# Icon file paths
ICON_PATH = "assets/icon.png"

# Mapping from UI prayer names to Aladhan API keys
PRAYER_NAME_MAP = {
    "Subuh": "Fajr",
    "Dzuhur": "Dhuhr",
    "Ashar": "Asr",
    "Maghrib": "Maghrib",
    "Isya": "Isha",
}

PRAYER_NAMES = list(PRAYER_NAME_MAP.keys())

# Complete city list (Provincial capitals + major cities)
CITIES = sorted(
    [
        "Ambon",
        "Balikpapan",
        "Banda Aceh",
        "Bandar Lampung",
        "Bandung",
        "Banjarbaru",
        "Banjarmasin",
        "Batam",
        "Batu",
        "Baturaja",
        "Bekasi",
        "Bengkulu",
        "Biak",
        "Binjai",
        "Blitar",
        "Bogor",
        "Bontang",
        "Bukittinggi",
        "Bitung",
        "Cilegon",
        "Cirebon",
        "Denpasar",
        "Depok",
        "Dumai",
        "Fakfak",
        "Garut",
        "Gorontalo",
        "Gresik",
        "Jakarta",
        "Jambi",
        "Jayapura",
        "Jombang",
        "Kediri",
        "Kendari",
        "Ketapang",
        "Kota Bharu",
        "Kotamobagu",
        "Kudus",
        "Kupang",
        "Lahat",
        "Lhokseumawe",
        "Lubuklinggau",
        "Luwuk",
        "Madiun",
        "Magelang",
        "Makassar",
        "Malang",
        "Mamuju",
        "Manado",
        "Manokwari",
        "Maumere",
        "Mataram",
        "Medan",
        "Merauke",
        "Metro",
        "Mojokerto",
        "Nganjuk",
        "Nunukan",
        "Padang",
        "Padang Panjang",
        "Padangpariaman",
        "Palangkaraya",
        "Palembang",
        "Palopo",
        "Palu",
        "Pangkal Pinang",
        "Panjang",
        "Parepare",
        "Pariaman",
        "Pasuruan",
        "Pati",
        "Pekalongan",
        "Pekanbaru",
        "Pematangsiantar",
        "Pontianak",
        "Prabumulih",
        "Probolinggo",
        "Purwokerto",
        "Purworejo",
        "Rangkasbitung",
        "Ruteng",
        "Sakatiga",
        "Salatiga",
        "Samarinda",
        "Sambas",
        "Semarang",
        "Serang",
        "Sibolga",
        "Sidoarjo",
        "Simalungun",
        "Singkawang",
        "Singaraja",
        "Situbondo",
        "Sofifi",
        "Solok",
        "Sorong",
        "Subang",
        "Sukabumi",
        "Sungai Penuh",
        "Surabaya",
        "Surakarta",
        "Tabanan",
        "Tanahmerah",
        "Tanjungbalai",
        "Tanjungpandan",
        "Tanjung Pinang",
        "Tanjung Selor",
        "Tangerang",
        "Tarakan",
        "Tasikmalaya",
        "Tebing Tinggi",
        "Ternate",
        "Tidore",
        "Timika",
        "Tomohon",
        "Tual",
        "Ubud",
        "Wamena",
        "Waingapu",
        "Yogyakarta",
    ]
)
